### ISSUE TITLE
How install v2ray into Suncomn 5g router ? 

### ISSUE THREAD

**Issue by ingnelson** [afandiazmi/Suncomm-Firmware#1]
Hello . 

How install v2ray into Suncomn 5g router ?

**Comment by afandiazmi** [comment]
Later we will implement the client to run v2ray, now is RnD project for this features.


All other project running is:
- Usage bandwith
- message capabilities/ SMS
- Telco Info
- Clash
- Load balancing
- Split tunnel
- scheduled reboot

**Comment by afandiazmi** [comment]
Later we will implement the client to run v2ray, now is RnD project for this features.

All other project running is:

Usage bandwith
message capabilities/ SMS
Telco Info
Clash
Load balancing
Split tunnel
scheduled reboot

**Comment by ingnelson** [comment]
Hello @afandiazmi .

I want to buy this router in this week and use your firmware.

I want to know if the CLASH that it is installed in your firmware supports  VMess and Trojan ?

I will wait for your reply, before to buy the router .

**Comment by ingnelson** [comment]
Hello @afandiazmi .

I want to buy this router in this week and use your firmware.

I want to know if the CLASH that it is installed in your firmware supports  VMess and Trojan ?

I will wait for your reply, before to buy the router .
