### ISSUE TITLE
CLASH 

### ISSUE THREAD

**Issue by ingnelson** [afandiazmi/Suncomm-Firmware#2]
Hello @afandiazmi .

I want to buy this router in this week and use your firmware.

I want to know if the CLASH that it is installed in your firmware supports  VMess and Trojan ?

Because my configuration that I use is Vmess or Trojan to have access to internet.

I will wait for your reply, before to buy the router .

**Comment by afandiazmi** [comment]
clash doesn't support for NSS acceleration, if we integrate that CLASH client into the suncomm, there will be lost of speed
